#!/usr/bin/env bash
# This script reads /etc/passwd and displays username:user_id:home_directory

while IFS=: read -r username _ userid _ _ home _; do
  echo "$username:$userid:$home"
done < /etc/passwd

