#!/usr/bin/env bash
# Script to display a formatted story based on /etc/passwd file content

while IFS=: read -r username password userid groupid userinfo home command; do
  echo "The user $username is part of the $groupid gang, lives in $home and rides $command. $userid's place is protected by the passcode $password, more info about the user here: $userinfo"
done < /etc/passwd

