#!/usr/bin/env bash
# Groups visitor IPs and HTTP status codes by occurrence count and sorts from highest to lowest

awk '{ count[$1, $9]++ } 
     END { 
       for (key in count) {
         split(key, arr, SUBSEP)
         printf "%7d %s %s\n", count[key], arr[1], arr[2]
       }
     }' apache-access.log | sort -nr

