#!/usr/bin/env bash

PID_FILE="/var/run/my_process.pid"
PROCESS_PATH="$(pwd)/manage_my_process"

case "$1" in
  start)
    "$PROCESS_PATH" &
    echo $! > "$PID_FILE"
    echo "manage_my_process started"
    ;;
  stop)
    if [ -f "$PID_FILE" ]; then
      kill "$(cat "$PID_FILE")"
      rm -f "$PID_FILE"
      echo "manage_my_process stopped"
    fi
    ;;
restart)
     if [ -f "$PID_FILE" ]; then
       kill "$($cat "$PID_FILE")"
       rm -f "$PID_FILE"
     fi
     "$PROCESS_PATH" &
     echo $! > "$PID_FILE"
     echo "manage_my_process restarted"
     ;;
   *)
     echo "Usage: manage_my_process {start|stop|restart}"
     exit 1
     ;; 
esac
