#!/usr/bin/env bash
# This script terminates all processes running the script '4-to_infinity_and_beyond'

#Get the PIDs of processes running '4-to_infinity_and_beyond'
readarray -t prog_pid < <(pgrep -f 4-to_infinity_and_beyond)
#Loop through each PID and send SIGTERM
for ((i = 0; i < ${#prog_pid[@]}; i++)); do
     kill -s SIGTERM "${prog_pid[i]}"
done
