#!/usr/bin/env bash
# This script stops the process running 4-to_infinity_and_beyond without using kill or killall

# Get the PID of the process
pid=$(pgrep -f 4-to_infinity_and_beyond)

# Send SIGTERM by writing to /proc/<pid>/status using bash builtin
# This terminates the process by sending SIGTERM (15)
[[ -n "$pid" ]] && echo SIGTERM > "/proc/$pid/attr/current"

