#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process without using kill or killall

pid=$(ps -eo pid,cmd | grep '[4]-to_infinity_and_beyond' | awk '{print $1}')
[ -n "$pid" ] && echo "Terminating PID $pid" && kill "$pid"

